/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 *
 * Edited by Tommy Zhang.
 *
 */

GtkWidget* create_gifclient (void);
GtkWidget* create_msgbox (const gchar*, const gchar*);
GtkWidget* create_About (void);
GtkWidget* create_Authen (void);
GtkWidget* create_Chat (void);
GtkWidget* create_AddContacts (void);
GtkWidget* create_Offline (void);
