/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"

GtkWidget *gifmain;

gint delete_event (GtkWidget *widget, GdkEvent *event, gpointer data)
{
  gtk_main_quit ();
  return (FALSE);
}


int
main (int argc, char *argv[])
{
  GtkWidget *gifclient;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  g_thread_init(NULL);	
  gdk_threads_init();	

  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gifclient = create_gifclient ();
  gtk_widget_show (gifclient);

  gifmain = gifclient;

  gtk_signal_connect (GTK_OBJECT (gifclient), "delete_event", GTK_SIGNAL_FUNC (delete_event), NULL);

  gdk_threads_enter();
  gtk_main ();
  gdk_threads_leave();

  return 0;
}

